// let num =+ prompt("Введите число")
// if (num>0)
// {
// 	console.log("Число было введено больше нуля")
// }
// else
// {
// 	console.log("Число было введено меньше нуля")
// }


//------------------(ИЛИ)------------------


// let num = Number(prompt("Введите число"));
// console.log(num);
// if(num>0)
// 	{
// 		console.log("Ваше число > 0")
// 	}
// else if (num<0)
// 	{
// 		console.log("Ваше число <0")
// 	}

//------------------(ИЛИ)------------------


// let num = Number(prompt("Введите число"));
// console.log(num);
// if(isNaN(num)) //Если пользователь вводит буквы вместо цифр (Returns a Boolean value that indicates whether a value is the reserved value NaN (not a number).)
// {
// 	console.log("Вы ввели неправильные данные")
// }
// if(num>0)
// 	{
// 		console.log("Ваше число > 0")
// 	}
// else if (num<0)
// 	{
// 		console.log("Ваше число < 0")
// 	}
// else
// {
// 	console.log("Ваше число = 0")
// }


//------------------(ИЛИ)------------------

// let num = Number(prompt("Введите число"));
// console.log(num);
// if(!num) //Если пользователь вводит буквы вместо цифр (Returns a Boolean value that indicates whether a value is the reserved value NaN (not a number).)
// {
// 	console.log("Вы ввели неправильные данные")
// }
// if(num>0)
// 	{
// 		console.log("Ваше число > 0")
// 	}
// else if (num<0)
// 	{
// 		console.log("Ваше число < 0")
// 	}
// else
// {
// 	console.log("Ваше число = 0")
// }

//------------------(ИЛИ)------------------


// console.log(typeof NaN)
// let num = Number(prompt("Введите число"));
// console.log(num);
// if(num === 0) // можно написать еще: if(num === null)
// {
// 	console.log("Ваше число = 0")
// }
// else if(!num) //В том случае, когда NaN, null ...
// 	{
// 		console.log("Вы ввели неверные данные")
// 	}
// else if(num>0)
// 	{
// 		console.log("Ваше число > 0")
// 	}
// else if (num<0)
// 	{
// 		console.log("Ваше число < 0")
// 	}
// else
// {
// 	console.log("Ваше число = 0")
// }

//------------------(ИЛИ)------------------

// console.log(typeof NaN)
// let num = prompt("Введите число");
// console.log(num);
// if(!Numbe(prompt("Введите число")) && num !=0 ) // можно н аписать еще: if(num === null)
// {
// 	console.log("Вы ввели неверное число")
// }
// else if(num>0)
// 	{
// 		console.log("Ваше число > 0")
// 	}
// else if (num<0)
// 	{
// 		console.log("Ваше число < 0")
// 	}
// else if (num === 0)
// {
// 	console.log("Ваше число = 0")
// }

//------------------(ИЛИ)------------------

// console.log(typeof NaN)

// let num = prompt("Введите число");
// console.log(num);

// if(!num || num !=0 ) // Если NaN, null, ""...
// {
// 	console.log("Вы ввели неверное число")
// }
// else if(num>0)
// 	{
// 		console.log("Ваше число > 0")
// 	}
// else if (num<0)
// 	{
// 		console.log("Ваше число < 0")
// 	}
// else if (num === 0)
// {
// 	console.log("Ваше число = 0")
// }

//------------------(ИЛИ)------------------

// console.log(typeof NaN)

// let num = prompt("Введите число");
// console.log(num);

// if(!Number(prompt("Введите число")) || num !=0) // Если NaN, null, ""...
// {
// 	console.log("Вы ввели неверное число")
// }
// else if(num>0)
// 	{
// 		console.log("Ваше число > 0")
// 	}
// else if (num<0)
// 	{
// 		console.log("Ваше число < 0")
// 	}
// else if (num === 0)
// {
// 	console.log("Ваше число = 0")
// }